# Include shared Makefile
include ../../Makefile.base

# Define project-specific variables
IMAGE_NAME = postgres_vanilla
CONTAINER_NAME = postgres_vanilla_container

# No additional targets needed for vanilla setup 